# Copyright (c) Aniskov N., Birillo A.

from src.main.python.pythonparser.pythonparser_3 import *
from src.main.python.inverse_parser.inverse_parser_3 import *


# The class provides general functions for the inverse parser tests
class InverseParserTestsUtil:

    @staticmethod
    def get_source_from_file(filename: str) -> str:
        """
        Just the source code from the file "filename"

        :param filename: path to .py file with source
        :return: source from provided file as string
        """
        return read_file_to_string(filename).strip('\n')

    @staticmethod
    def source_to_xml_to_source(filename: str) -> str:
        """
        Code generated by following procedure:

        [original code] -> [Python AST] -> [XML AST] by pythonparser_3
        [XML AST] -> [generated code] by inverse_parser_3

        :param filename:  path to .py file with source
        :return: generated source by the procedure described above as string
        """
        xml_str = json2xml(parse_file(filename))
        inverse_parser = InverseParser(xml_str=xml_str)
        return inverse_parser.get_source().strip('\n')
